[platformio]
default_envs = bluepill_f103c8
src_dir = Core/Src
include_dir = Core/Inc

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube

; Reuse STM32CubeIDE generated layout
; Keep linker behavior aligned with current project
board_build.ldscript = STM32F103C8TX_FLASH.ld
board_build.stm32cube.custom_config_header = yes

build_flags =
    -DUSE_HAL_DRIVER
    -DSTM32F103xB
    -ICore/Inc
    -IDrivers/STM32F1xx_HAL_Driver/Inc
    -IDrivers/STM32F1xx_HAL_Driver/Inc/Legacy
    -IDrivers/CMSIS/Include
    -IDrivers/CMSIS/Device/ST/STM32F1xx/Include
    -Wl,-u,_printf_float

; Avoid duplicate system file symbol with framework-provided startup/system
build_src_filter =
    +<*>
    -<system_stm32f1xx.c>

upload_protocol = serial
upload_port = COM3
upload_speed = 115200

monitor_port = COM3
monitor_speed = 115200